### ISSUE TITLE
Failed to transcode some video files

### ISSUE THREAD

**Issue by Ma7moudHatem** [linkedin/LiTr#102]
I have the following video file, which I need to transcode it by either add an overlay above it or change the bitrate of the video,
https://drive.google.com/file/d/1Y6t1jIchWbNl_f71MA1mq56jrKjxgHTs/view 
 I tried the demo app, and when clicking on the transcode button, it keeps processing, and after I debugged the issue, I found that `LiTr` will throw a `BufferOverflowException`, and when it tries to release the `MediaMuxerMediaTarget`, it also throws an exception in the `release()` method, so the `listeners` will not receive the stop status with the failed state.

NOTES:
1. I'm currently using` litr 1.4.9`
2. I transcode the video to `video/avc` format, with a video bitrate 1.5Mb/s
3. I transcode the audio to `audio/mp4a-latm` format, with an audio bitrate 128Kb/s
4. I think the issue related to the **audio track**, so when just transcoding the audio track, the issue happened.

What I need:
 1. Please if you can fix the transcoding issue related to the attached video file.
 2. Make sure that if an exception happened in the `release(boolean success)` method inside `TransformationJob` class will be caught and handled.

**Comment by izzytwosheds** [comment]
Thank you for reporting! I will look into this.

**Comment by izzytwosheds** [comment]
Which device/OS version are you using? I cannot reproduce it on Samsung Note 10. 
Can you also post the logcat?

**Comment by Ma7moudHatem** [comment]
As I mentioned before, the issue happened only if I transcoded the audio track, and after some debugging, I found the line of code that causes the issue, In `renderFrame` method inside `PassthroughSoftwareRenderer` class, at line 62  `outputFrame.buffer.put(inputBuffer);` , an exception(`BufferOverflowException`) will be thrown, because somehow the `outputFrame buffer`'s remaining is less than the `inputBuffer` remaining, for example, the outputFrame buffer remaining is **4096** and the inputBuffer remaining is **12250**.

**Comment by Ma7moudHatem** [comment]
@izzytwosheds please, when you will release this pull request https://github.com/linkedin/LiTr/pull/103 ? which will fix the current issue.

**Comment by izzytwosheds** [comment]
Released it, should be available now.
