### ISSUE TITLE
Could not find com.linkedin.android.litr:litr:1.4.12

### ISSUE THREAD

**Issue by Ma7moudHatem** [linkedin/LiTr#110]
I have updated the `litr` dependency to the latest version `1.4.12`,  but I got the following error:
`Could not find com.linkedin.android.litr:litr:1.4.12.`
I think the library still not published in the maven repo.

**Comment by izzytwosheds** [comment]
Sorry, didn't configure the release correctly, so publishing it failed. Fixed now.
