### ISSUE TITLE
Video cropping feature

### ISSUE THREAD

**Issue by tengyeekong** [linkedin/LiTr#112]
Thanks for the awesome library! May I know will there be any chance LiTr would be adding video cropping feature? Just a simple cropping feature with ratio as input and crop with max resolution size from the center. Thanks!

**Comment by izzytwosheds** [comment]
Glad to hear you are enjoying LiTr! 
You can already do this by using `DefaultVideoFrameRenderFilter` with a `Transform` that positions your source video outside of target video frame. See how `TransformationPresenter.startVideoOverlayTransformation` method in demo app places source video onto target video frame.

**Comment by tengyeekong** [comment]
Noted, thanks a lot!

**Comment by tengyeekong** [comment]
@izzytwosheds sorry, I'm not able to crop a video into different width and height while maintaining the content aspect ratio by using `DefaultVideoFrameRenderFilter` with a `Transform`. For example cropping a 3:4 video to 1:1. `Transform` only scales my video.

**Comment by izzytwosheds** [comment]
I added a new demo to do square center crop of video. It is a little hacky, but works and should give you a good starting point:
https://github.com/linkedin/LiTr/commit/648b57bf54a56abe581b8fb9769402ba0e7e2fce#diff-1564a2e71ec4d391e725f5ab74e828fa4fc45e43e1f8076d9c9c79ef27ea8d66R212

The trick is to scale the video correctly, accounting for both aspect ratio and orientation.

**Comment by tengyeekong** [comment]
It's working! Thanks a lot!
