### ISSUE TITLE
Output Video is Stretched.

### ISSUE THREAD

**Issue by oluwabajio** [linkedin/LiTr#117]
i implemented the second example from the demo procided. 

   VIDEO_OVERLAY_GL(R.string.demo_case_free_transform_video_gl, "FreeTransformVideoGl", new FreeTransformVideoGlFragment()),

The output video is stretched. How can i make it not stretch.

check it out here -> https://ibb.co/N6JhvWN

**Comment by oluwabajio** [comment]
How do i set the aspect ratio please

**Comment by izzytwosheds** [comment]
You should define video width/height with a desired aspect ratio

**Comment by oluwabajio** [comment]
Thanks for your response. i would greatly appreciate if you can point me to the correct class or object where i need to set the width/height property

**Comment by izzytwosheds** [comment]
`TransformationPresenter` has several useful methods you can use

**Comment by oluwabajio** [comment]
Thanks, i solved the aspect ratio issue by varying the width and height in the TargetMedia.java class.

    public static final int DEFAULT_VIDEO_WIDTH = 1280;
    public static final int DEFAULT_VIDEO_HEIGHT = 720;
