### ISSUE TITLE
Can't change the framerate of video

### ISSUE THREAD

**Issue by quangtd95** [linkedin/LiTr#120]
Hi everyone, I need to adjust FPS of video. I'm using a below code and expect new fps will be **25**
```
        MediaTransformer mediaTransformer = new MediaTransformer(context);
        MediaExtractor mediaExtractor = new MediaExtractor();
        mediaExtractor.setDataSource(input.getPath());
        MediaFormat inputFormat = selectVideoTrack(mediaExtractor);

        MediaFormat mediaFormat = MediaFormat.createVideoFormat(
                MediaFormat.MIMETYPE_VIDEO_AVC,
                inputFormat.getInteger(MediaFormat.KEY_WIDTH),
                inputFormat.getInteger(MediaFormat.KEY_HEIGHT));
        
        mediaFormat.setInteger(MediaFormat.KEY_BIT_RATE, DEFAULT_VIDEO_BITRATE);
        mediaFormat.setInteger(MediaFormat.KEY_I_FRAME_INTERVAL, DEFAULT_KEY_FRAME_INTERVAL);
        mediaFormat.setInteger(MediaFormat.KEY_FRAME_RATE, 25);
        mediaTransformer.transform(UUID.randomUUID().toString(),
                input,
                outputPath,
                mediaFormat,
                null,
                listener,
                null
        );
```

the above code works successfully, but as per checking the output file,  it still keeps the same fps as input. ( nothing change). fps still be **29.90 fps**
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'adjust_frame_rate_1621235937540.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2021-05-17T07:19:03.000000Z
    com.android.version: 9
  Duration: 00:00:21.00, start: 0.000000, bitrate: 5081 kb/s
  Stream #0:0(eng): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p(tv, smpte170m/bt470bg/smpte170m), 576x1024, 4949 kb/s, SAR 1:1 DAR 9:16, 29.90 fps, 30 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      creation_time   : 2021-05-17T07:19:03.000000Z
      handler_name    : VideoHandle
      vendor_id       : [0][0][0][0]
```
Can anyone help on this?

**Comment by izzytwosheds** [comment]
Do you need to decrease frame rate or also increase it?

**Comment by quangtd95** [comment]
I need to decrease fps. From 30 to 25

Vào 04:01, T.4, 19 Th5, 2021 Izzat Bahadirov ***@***.***> đã
viết:

**Comment by alexvasilkov** [comment]
I also would like to limit frame rate of the video during transcode, but it turns out original frame rate is enforced, [see here](https://github.com/linkedin/LiTr/blob/cfb9cb8/litr/src/main/java/com/linkedin/android/litr/transcoder/VideoTrackTranscoder.java#L71).

I don't think there is a good reason to increase the frame rate, and decrease of the frame rate can be done similar to [this project](https://github.com/natario1/Transcoder/blob/bf4ce2c/lib/src/main/java/com/otaliastudios/transcoder/internal/video/FrameDropper.kt).

**Comment by izzytwosheds** [comment]
Frame rate can now be reduced, thanks to @niekdev 's implementation.
