### ISSUE TITLE
How can we add multiple water marks simultaneously

### ISSUE THREAD

**Issue by pawaom** [linkedin/LiTr#121]
How can we add multiple water marks simultaneously

`VideoWatermarkFragment.java`  provides example of adding water mark, but is there a way to add multiple watermarks, say we need to add 5-6 watermarks, how can we do that. Will it be a lightweight  sollution.

**Comment by izzytwosheds** [comment]
That is very easy. Just use multiple `BitmapOverlayFilter`s or `FrameSequenceAnimationOverlayFilter`s (for animated watermarks) - `Renderer` takes a list of `GlFilter`s and applies them in order.
