### ISSUE TITLE
mediaCodec.configure fails due to using an incorrect media format

### ISSUE THREAD

**Issue by JohannBlake** [linkedin/LiTr#124]
The demo app can't configure the mediacodec with the format the app is creating:

`mediaCodec.configure(mediaFormat, surface, null, isEncoder ? MediaCodec.CONFIGURE_FLAG_ENCODE : 0);`

The mediaFormat parameter looks like this:

`{color-format=2130708361, i-frame-interval=5, durationUs=60066066, mime=video/avc, profile=1, width=1440, bitrate=4003213, frame-rate=30, height=2614}`

surface parameter is null and the isEncoder parameter is set to true.

Using my own app where I am able to encode a video, the mediaFormat looks like this:

`{color-format=2130708361, i-frame-interval=1, mime=video/avc, width=1440, bitrate=4000000, frame-rate=30, height=2614}`

The difference between the format that the LiTr code creates and the one my code creates are:

* The "i-frame-interval" is set to 5 in LiTr while it is set to 1 in my code.
* The LiTr sets the profile to 1, while in my app, no profile is specified.

If I modify the code in LiTr to create the same media format as what is being used in my app, the LiTr demo works fine. It turns out that setting the profile parameter is the root of the problem. Changing the "i-frame-interval" parameter didn't have any effect. I think the code should be modified to not set the profile parameter, although maybe that is something that varies with Android versions. If that is the case, then it should not be set for Android 11.

I'm running this on a Pixel 2 device with Android 11.

**Comment by izzytwosheds** [comment]
Thank you for the feedback! I will change the demo app code. I was experimenting with higher level profiles and left my experimental code in. Nice catch!
