### ISSUE TITLE
Can we add custom audio over same video that means we override the current audio and after that we compressor the same video?

### ISSUE THREAD

**Issue by amitagnihotri** [linkedin/LiTr#128]
I have question:

Can we add custom audio over same video that means we override the current audio and after that we compressor the same video?

This feature is available in this library. If not then please guide me how can I will achieve this point using this library or if yes then please share the method with me.

Thanks

**Comment by izzytwosheds** [comment]
Yes, you should be able to replace audio track in video. You can do that by defining two `TrackTransform`s:
 - one that takes video from file 1 (create MediaSource that takes only a video track)
 - another one that takes audio from file 2 
 - single MediaTarget for both sources, make sure to correctly set target tracks
 Make sure to set trimming for audio track (if it is longer than video track) to match video track's duration.
Let me know how this works out.

**Comment by amitagnihotri** [comment]
Thanks for your response.

But Can you please share a method for fetching video track only from video file.
Rest I agree I have 2 files 1 for video and 2 for audio.
So Can you please share the method for fetching Video track only and audio track.
And last please share those method which one i will pass both audio and video parameter.
So result with custom audio with same video with compress.

**Comment by amitagnihotri** [comment]
Hello Izzat Bahadirov,

Please guide me.
And share the method how I will achieve this?

**Comment by izzytwosheds** [comment]
You will need to `TrackTransform`s - one will take video file as a source, another one will take audio file as a source, and both with have the same target. Something like this:
 
MediaSource videoMediaSource = new MediaExtractorMediaSource(context, sourceVideoUri);
MediaSource audioMediaSource = new MediaExtractorMediaSource(context, sourceAudioUri);
MediaTarget combinedMediaTarget = new MediaMuxerMediaTarget(outputPath, 2, rotation, MediaMuxer.OutputFormat.MUXER_OUTPUT_MPEG_4);

TrackTransform videoTrackTransform = new TrackTransform.Builder(videoMediaSource, 0, combinedMediaTarget)
.setDecoder(new MediaCodecDecoder())
.setEncoder(new MediaCodecEncoder())
.setTargetTrack(0)
.setRenderer(new GlVideoRenderer())
.setTargetFormat(targetVideoFormat)
.build()

TrackTransform audioTrackTransform = new TrackTransform.Builder(audioMediaSource, 0, combinedMediaTarget)
.setDecoder(new MediaCodecDecoder())
.setEncoder(new MediaCodecEncoder())
.setTargetTrack(1)
.setTargetFormat(targetAudioFormat)
.build()

List<TrackTransform> trackTransforms = new ArrayList<>()
trackTransforms.add(videoTrackTransform)
trackTransforms.add(audioTrackTransform)

mediaTransformer.transform(requestId, trackTransforms, listener, MediaTransformer.GRANULARITY_DEFAULT)

**Comment by izzytwosheds** [comment]
Target formats can be `null` if you want to write out tracks without any transformation.

**Comment by amitagnihotri** [comment]
Hello @izzytwosheds 


    public void startTransformation(@NonNull Uri sourceVideoUri,
                                    @NonNull Uri sourceAudioUri,
                                    @NonNull SourceMedia sourceMedia,
                                    @NonNull TargetMedia targetMedia,
                                    @NonNull TargetMedia targetAudioMedia,
                                    @NonNull TrimConfig trimConfig,
                                    @NonNull TransformationState transformationState,
                                    OnFileCompress onFileCompress) {
        if (targetMedia.getIncludedTrackCount() < 1) {
            return;
        }

        if (targetMedia.targetFile.exists()) {
            targetMedia.targetFile.delete();
        }
        if (targetAudioMedia.targetFile.exists()) {
            targetAudioMedia.targetFile.delete();
        }

        transformationState.requestId = UUID.randomUUID().toString();
        MediaTransformationListener transformationListener = new MediaTransformationListener(context,
                transformationState.requestId,
                transformationState, onFileCompress);

        try {
            int videoRotation = 0;
            for (MediaTrackFormat trackFormat : sourceMedia.tracks) {
                if (trackFormat.mimeType.startsWith("video/mp4")) {
                    videoRotation = ((VideoTrackFormat) trackFormat).rotation;
                    break;
                }
            }
            MediaSource videoMediaSource = new MediaExtractorMediaSource(context, sourceVideoUri);
            MediaSource audioMediaSource = new MediaExtractorMediaSource(context, sourceAudioUri);

            MediaRange mediaRange = trimConfig.enabled
                    ? new MediaRange(
                    TimeUnit.MILLISECONDS.toMicros((long) (trimConfig.range.get(0) * 1000)),
                    TimeUnit.MILLISECONDS.toMicros((long) (trimConfig.range.get(1) * 1000)))
                    : new MediaRange(0, Long.MAX_VALUE);

            MediaTarget combinedMediaTarget = new MediaMuxerMediaTarget(targetMedia.targetFile.getPath(),
                    2,
                    videoRotation,
                    MediaMuxer.OutputFormat.MUXER_OUTPUT_MPEG_4);

            TrackTransform videoTrackTransform = null;
            TrackTransform audioTrackTransform = null;

            for (TargetTrack targetTrack : targetMedia.tracks) {
                if (!targetTrack.shouldInclude) {
                    continue;
                }

                 videoTrackTransform = new TrackTransform.Builder(videoMediaSource,
                        0,
                         combinedMediaTarget)
                        .setDecoder(new MediaCodecDecoder())
                        .setEncoder(new MediaCodecEncoder())
                        .setTargetTrack(0)
                        .setRenderer(new GlVideoRenderer(createGlFilters(sourceMedia,
                                (TargetVideoTrack) targetTrack,
                                0.56f,
                                new PointF(0.6f, 0.4f),
                                30)))
                        .setTargetFormat(createMediaFormat(targetTrack))
                        .build();
            }

            for (TargetTrack targetTrack : targetAudioMedia.tracks) {
                if (!targetTrack.shouldInclude) {
                    continue;
                }
                audioTrackTransform = new TrackTransform.Builder(audioMediaSource,
                        0,
                        combinedMediaTarget)
                        .setDecoder(new MediaCodecDecoder())
                        .setEncoder(new MediaCodecEncoder())
                        .setTargetTrack(1)
                        .setTargetFormat(createMediaFormat(targetTrack))
                        .build();
            }
            List trackTransforms = new ArrayList<>();
            trackTransforms.add(videoTrackTransform);
            trackTransforms.add(audioTrackTransform);
            mediaTransformer.transform(transformationState.requestId,
                    trackTransforms,
                    transformationListener,
                    MediaTransformer.GRANULARITY_DEFAULT);


             } catch (MediaTransformationException ex) {
            Log.e(TAG, "Exception when trying to perform track operation", ex);
        }
    }

  Please check this method and update me if I m doing something wrong.

**Comment by izzytwosheds** [comment]
This looks right. Does it work?

**Comment by amitagnihotri** [comment]
Hello @izzytwosheds 
Receiving a error when i pass the value.
 java.lang.ClassCastException: TargetAudioTrack cannot be cast to TargetVideoTrack
 
     videoTrackTransform = new TrackTransform.Builder(videoMediaSource,
                        0,
                         combinedMediaTarget)
                        .setDecoder(new MediaCodecDecoder())
                        .setEncoder(new MediaCodecEncoder())
                        .setTargetTrack(0)
                        .setRenderer(new GlVideoRenderer(createGlFilters(sourceMedia,
                                (TargetVideoTrack) targetTrack,
                                0.56f,
                                new PointF(0.6f, 0.4f),
                                30)))
                        .setTargetFormat(createMediaFormat(targetTrack))
                        .build();

App is crash on this line    .setTargetTrack(0)

Can you please check and guide me where I m wrong and where I will update my method so I will receive a correct input.

**Comment by amitagnihotri** [comment]
Hello @izzytwosheds

Please guide me about this. Otherwise I will stuck on this. Please check my function where I m wrong and please correct me.
If this feature is available in this library.

**Comment by izzytwosheds** [comment]
Are you sure that crash is not happening on `.setRenderer` line? `createGlFilters` method expects `TargetVideoTrack` but seems to be getting an instance of `TargetAudioTrack` which causing an exception. Your logic tries to create `videoTrackTransform` for every track in source video file, which could also contain audio tracks. A better logic would be to do an instance check for `TargetVideoTrack` and pick the first video track.

**Comment by amitagnihotri** [comment]
Hello @izzytwosheds
Thanks for response. I agree with you regarding  .setRenderer(new GlVideoRenderer(createGlFilters(sourceMedia,
                                (TargetVideoTrack) targetTrack,
                                0.56f,
                                new PointF(0.6f, 0.4f),
                                30)))
                             
but in case i pass the TargetVideoTrack object please check my function in this i have implement 2 loops 
1. Loop for Video
2. Loop for Audio

1. for (TargetTrack targetTrack : targetMedia.tracks) {
                if (!targetTrack.shouldInclude) {
                    continue;
                }

                 videoTrackTransform = new TrackTransform.Builder(videoMediaSource,
                        0,
                         combinedMediaTarget)
                        .setDecoder(new MediaCodecDecoder())
                        .setEncoder(new MediaCodecEncoder())
                        .setTargetTrack(0)
                        .setRenderer(new GlVideoRenderer(createGlFilters(sourceMedia,
                                (TargetVideoTrack) targetTrack,
                                0.56f,
                                new PointF(0.6f, 0.4f),
                                30)))
                        .setTargetFormat(createMediaFormat(targetTrack))
                        .build();
            }



2.    for (TargetTrack targetTrack : targetAudioMedia.tracks) {
                if (!targetTrack.shouldInclude) {
                    continue;
                }
                audioTrackTransform = new TrackTransform.Builder(audioMediaSource,
                        0,
                        combinedMediaTarget)
                        .setDecoder(new MediaCodecDecoder())
                        .setEncoder(new MediaCodecEncoder())
                        .setTargetTrack(1)
                        .setTargetFormat(createMediaFormat(targetTrack))
                        .build();
            }


after both loops

 List trackTransforms = new ArrayList<>();
            trackTransforms.add(videoTrackTransform);
            trackTransforms.add(audioTrackTransform);

mediaTransformer.transform(transformationState.requestId,
                    trackTransforms,
                    transformationListener,
                    MediaTransformer.GRANULARITY_DEFAULT);




Again i m sharing my full functions


public void startTransformation(@NonNull Uri sourceVideoUri,
                                    @NonNull Uri sourceAudioUri,
                                    @NonNull SourceMedia sourceMedia,
                                    @NonNull TargetMedia targetMedia,
                                    @NonNull TargetMedia targetAudioMedia,
                                    @NonNull TrimConfig trimConfig,
                                    @NonNull TransformationState transformationState,
                                    OnFileCompress onFileCompress) {
        if (targetMedia.getIncludedTrackCount() < 1) {
            return;
        }

        if (targetMedia.targetFile.exists()) {
            targetMedia.targetFile.delete();
        }
        if (targetAudioMedia.targetFile.exists()) {
            targetAudioMedia.targetFile.delete();
        }

        transformationState.requestId = UUID.randomUUID().toString();
        MediaTransformationListener transformationListener = new MediaTransformationListener(context,
                transformationState.requestId,
                transformationState, onFileCompress);

        try {
            int videoRotation = 0;
            for (MediaTrackFormat trackFormat : sourceMedia.tracks) {
                if (trackFormat.mimeType.startsWith("video/mp4")) {
                    videoRotation = ((VideoTrackFormat) trackFormat).rotation;
                    break;
                }
            }
            MediaSource videoMediaSource = new MediaExtractorMediaSource(context, sourceVideoUri);
            MediaSource audioMediaSource = new MediaExtractorMediaSource(context, sourceAudioUri);

            MediaRange mediaRange = trimConfig.enabled
                    ? new MediaRange(
                    TimeUnit.MILLISECONDS.toMicros((long) (trimConfig.range.get(0) * 1000)),
                    TimeUnit.MILLISECONDS.toMicros((long) (trimConfig.range.get(1) * 1000)))
                    : new MediaRange(0, Long.MAX_VALUE);

            MediaTarget combinedMediaTarget = new MediaMuxerMediaTarget(targetMedia.targetFile.getPath(),
                    2,
                    videoRotation,
                    MediaMuxer.OutputFormat.MUXER_OUTPUT_MPEG_4);

            TrackTransform videoTrackTransform = null;
            TrackTransform audioTrackTransform = null;

            for (TargetTrack targetTrack : targetMedia.tracks) {
                if (!targetTrack.shouldInclude) {
                    continue;
                }

                 videoTrackTransform = new TrackTransform.Builder(videoMediaSource,
                        0,
                         combinedMediaTarget)
                        .setDecoder(new MediaCodecDecoder())
                        .setEncoder(new MediaCodecEncoder())
                        .setTargetTrack(0)
                        .setRenderer(new GlVideoRenderer(createGlFilters(sourceMedia,
                                (TargetVideoTrack) targetTrack,
                                0.56f,
                                new PointF(0.6f, 0.4f),
                                30)))
                        .setTargetFormat(createMediaFormat(targetTrack))
                        .build();
            }

            for (TargetTrack targetTrack : targetAudioMedia.tracks) {
                if (!targetTrack.shouldInclude) {
                    continue;
                }
                audioTrackTransform = new TrackTransform.Builder(audioMediaSource,
                        0,
                        combinedMediaTarget)
                        .setDecoder(new MediaCodecDecoder())
                        .setEncoder(new MediaCodecEncoder())
                        .setTargetTrack(1)
                        .setTargetFormat(createMediaFormat(targetTrack))
                        .build();
            }

            List trackTransforms = new ArrayList<>();
            trackTransforms.add(videoTrackTransform);
            trackTransforms.add(audioTrackTransform);
            mediaTransformer.transform(transformationState.requestId,
                    trackTransforms,
                    transformationListener,
                    MediaTransformer.GRANULARITY_DEFAULT); 
        } catch (MediaTransformationException ex) {
            Log.e(TAG, "Exception when trying to perform track operation", ex);
        }
    }

according to me i think i m not passing anything wrong parameter. 
Please check this function and guide me where i m doing wrong.

**Comment by amitagnihotri** [comment]
And also i m requesting for you can you please create a one function for me like both conversions video and audio doing and after that i have received a result
 mediaTransformer.transform(transformationState.requestId,
                trackTransforms,
                transformationListener,
                MediaTransformer.GRANULARITY_DEFAULT); 

for this method.
Reason for this its already take so much time for discussion. And i understand in my function may be minor or may be big problem but in the end we need a perfect result. So like i have read the feature for this library provide this feature(add custom audio over same video that means we override the current audio and after that we compressor the same video).

Please give me us small sample. Example on button click we pick a video and audio for same length and after that we implement above feature. Its very easy for me to check where my function was perform wrong things.

its good for both like we already discuss this point around more than 30 days.

**Comment by amitagnihotri** [comment]
E/TransformationPresenter: Exception when trying to perform track operation
    com.linkedin.android.litr.exception.MediaTargetException: java.io.FileNotFoundException: /storage/emulated/0/Movies/transcoded_VID-20210811-WA0000.mp4: open failed: EACCES (Permission denied)Media transformation failed for job id: null
    Failed to open the media target for write.
    Output file path or Uri encoded string: /storage/emulated/0/Movies/transcoded_VID-20210811-WA0000.mp4
    MediaMuxer output format: 0
        at com.linkedin.android.litr.io.MediaMuxerMediaTarget.<init>(MediaMuxerMediaTarget.java:84)
        at com.compressor.data.TransformationPresenter.startTransformation(TransformationPresenter.java:89)

Facing this issue

**Comment by izzytwosheds** [comment]
Let me take a look at this. I will get back to you shortly.

**Comment by amitagnihotri** [comment]
Thanks I will wait your response.

**Comment by izzytwosheds** [comment]
I pushed a new demo option in demo app that does what you need - extracts video track from one file, audio track from another and muxes them into one file.

**Comment by amitagnihotri** [comment]
Thanks I will Check

**Comment by amitagnihotri** [comment]
Thanks Buddy its working fine.
Demo working fine now same thing I will implement in our code. Once Again Thanks

**Comment by amitagnihotri** [comment]
Yes  @izzytwosheds.
And It's working fine from my end also. Thanks again

**Comment by amitagnihotri** [comment]
And please close the ticket. Problem solved regarding this ticket. If any information need more then I will add  a comment. 
Rest everything working fine.

**Comment by izzytwosheds** [comment]
You're welcome! Thank you for using LiTr!

**Comment by amitagnihotri** [comment]
Hello @izzytwosheds 
Facing issue in android 8 and android 9 during calling Mux Video and Audio Tracks.

Error:
E/TransformationJob: Transformation job error
    com.linkedin.android.litr.exception.TrackTranscoderException: Failed to configure encoder codec.Media transformation failed for job id: null
    Media format: {mime=video/avc, frame-rate=18, color-format=2130708361, height=720, width=1280, profile=1, bitrate=14641839, durationUs=10024611, i-frame-interval=5}
    Diagnostic info: null
        at com.linkedin.android.litr.utils.CodecUtils.getAndConfigureCodec(CodecUtils.java:217)
        at com.linkedin.android.litr.codec.MediaCodecEncoder.init(MediaCodecEncoder.java:41)
        at com.linkedin.android.litr.transcoder.VideoTrackTranscoder.initCodecs(VideoTrackTranscoder.java:74)
        at com.linkedin.android.litr.transcoder.VideoTrackTranscoder.<init>(VideoTrackTranscoder.java:64)
        at com.linkedin.android.litr.transcoder.TrackTranscoderFactory.create(TrackTranscoderFactory.java:78)
        at com.linkedin.android.litr.TransformationJob.createTrackTranscoders(TransformationJob.java:175)
        at com.linkedin.android.litr.TransformationJob.transform(TransformationJob.java:97)
        at com.linkedin.android.litr.TransformationJob.run(TransformationJob.java:77)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
     Caused by: java.lang.IllegalStateException
        at com.linkedin.android.litr.utils.CodecUtils.createAndConfigureCodec(CodecUtils.java:283)
        at com.linkedin.android.litr.utils.CodecUtils.getAndConfigureCodecByType(CodecUtils.java:230)
        at com.linkedin.android.litr.utils.CodecUtils.getAndConfigureCodec(CodecUtils.java:205)
        
        
        
        Can you please check? And guide us
