### ISSUE TITLE
How to make a video out array of bitmaps?

### ISSUE THREAD

**Issue by kartik1225** [linkedin/LiTr#129]
I have an animation view and from that animation view I can get the `bitmaps` frame by frame so Is there any way I can give the frame as the animation goes and somehow `LiTr` will encode the video?

Thanks in advance ( Such a gold library thank you for making this 🍰 )

**Comment by izzytwosheds** [comment]
Thank you! Glad that LiTr is helping you with your work!

Yes, you can convert an animation into a video using LiTr. The trick is to use a combination of `MockVideoMediaSource`, `PassthroughDecoder` and `FrameSequenceAnimationOverlayFilter` from `litr-filters`. You will basically be creating a video with empty frames and drawing your animation frames on top of it. 

See how `TransformationPresenter.createEmptyVideo` method does it in demo app. Let me know if you have any questions.

**Comment by kartik1225** [comment]
Thank you so much for taking the time and writing a detailed answer!

I will give it a try. 🙌🏻
