### ISSUE TITLE
Feature Request : Overlay Audio over Video(already containing Audio)

### ISSUE THREAD

**Issue by pawaom** [linkedin/LiTr#131]
Currently this code allows only to replace or remove audio of video, there is no support for overlaying audio over video which already has audio.

According to this

https://developer.android.com/reference/android/media/MediaMuxer#History ,

now Muxing Multiple Video/Audio Tracks is allowed for Api 26 and higher for an mp4 container.

I have been looing for examples , about using this feature, but cannot find any code. Can you please provide sample code and include this feature in future releases.

**Comment by izzytwosheds** [comment]
I am pretty sure that this new `MediaMuxer` capability can be used without any modifications to LiTr. You can add a new track from a different file using an additional `TrackTransform`. That will not, however, mux (overlay) audio tracks into one. It will add another audio track that player can select, similar to adding a new language to a movie.

**Comment by pawaom** [comment]
thanks for the reply I am Also studying this code

https://github.com/ZeroOneZeroR/android_audio_mixer

This does overlay audio over audio 

If you could incorporate similar feature in Litr it would be great.

**Comment by izzytwosheds** [comment]
This is now available in LiTr. Use `AudioOverlayFilter` to overlay audio file over audio track.
