### ISSUE TITLE
Flip horizontal/vertical feature

### ISSUE THREAD

**Issue by arunkr83** [linkedin/LiTr#134]
Please add video horizontal/vertical flipping feature.

**Comment by izzytwosheds** [comment]
LiTr can already do this. Use `DefaultVideoFrameRenderFilter` and pass in `Transform(PointF(0, -1), PointF(0.5f, 05f), 0)` Negative size value flips the video.

**Comment by arunkr83** [comment]
> LiTr can already do this. Use `DefaultVideoFrameRenderFilter` and pass in `Transform(PointF(0, -1), PointF(0.5f, 05f), 0)` Negative size value flips the video.

Thank you.,.
