### ISSUE TITLE
DefaultAudioSink: Discontinuity detected

### ISSUE THREAD

**Issue by manishkummar21** [linkedin/LiTr#137]
I facing an issue after I mux selected audio with video, I played the target file using exoplayer and I am getting this error while playing 

E/DefaultAudioSink: Discontinuity detected [expected 2159455, got 2384399]
E/DefaultAudioSink: Discontinuity detected [expected 4079456, got 4291337] ....

Can u please help me on this

**Comment by izzytwosheds** [comment]
Sorry it took a while to look into this. Looking into this now. I am seeing this, too.

**Comment by izzytwosheds** [comment]
This is fixed in new `AudioRenderer`, along with bunch of other improvements. It is available on main branch and will be in the next release of LiTr.
Thank you for reporting this, this was a pretty serious bug.
