### ISSUE TITLE
getting file size by providing two time slots.

### ISSUE THREAD

**Issue by uzairmughal3397** [linkedin/LiTr#152]
Hi,
Is it possible to get file size estimated or actual by providing starting and ending point (e.g. 02:00 to 04:00) along with file. 
and what is the purpose of getEstimatedTargetVideoSize().
Is it estimated size of whole file or what.

**Comment by izzytwosheds** [comment]
It is supposed to account for start/end selection. I will take a look, there might be a bug in logic.

**Comment by uzairmughal3397** [comment]
Sure let me know when you update the logic

**Comment by izzytwosheds** [comment]
Are you using size estimation method in `MediaTransformer` or in `TranscoderUtils`? The one in `MediaTransformer` is old one and doesn't take `MediaRange` into account.

**Comment by uzairmughal3397** [comment]
Yes I would have to wait for release.

**Comment by izzytwosheds** [comment]
This should be available in latest release 1.4.17
