### ISSUE TITLE
Convert audio format. Can I?

### ISSUE THREAD

**Issue by james04gr** [linkedin/LiTr#156]
In my Android application i use the MediaRecorder to record an audio clip in 3gp extension. I want to convert that clip to mp3 right after and upload it to server. I wander if the LiTr library can do such thing
Thank you

**Comment by izzytwosheds** [comment]
I am pretty sure that you can, as long as device can play back the source format and record into a target format. It is a matter of figuring out the target parameters. I will play around with this, will let you know what I find.

**Comment by james04gr** [comment]
Excellent. I really appreciate it

**Comment by izzytwosheds** [comment]
So I looked into this, and it looks like that Android does not support writing into MP3 file out of the box. Instead, we can transcode into AAC format (next generation codec to MP3, with better compression at same quality) and write into MP4 file. It will look like an MP4 video with audio track only and will play fine. I added a new demo in sample app that does that. Will this work for you?
There seems to be a bug with audio encoder dropping frames, transcoded audio sounds corrupted. I will work on fixing this.

**Comment by james04gr** [comment]
Hello. Yes, i guess that would work since Android can create AAC format through the MediaRecorder and AAC is an universal acceptable format. I didn't exactly understood the last issue that you mentioned but since you are on it, its ok!
Let me know when its fixed!
Thank you very much

**Comment by izzytwosheds** [comment]
Since MediaRecorder can record in AAC format, and your backend can accept AAC, do you still need to transcode using LiTr instead of just recording into AAC? I will still fix the bug, just curious.

**Comment by james04gr** [comment]
Hello.
Yeah, its true that Android can record AAC and Backend can also accept AAC, but there are some other factors that have not been evaluated and its about the Business Logic of the whole app. So i would be really grateful if you could please make it work so i could have an alternative but also to know who its done in case of someone else needs that
Thank you

**Comment by izzytwosheds** [comment]
We have made bunch of audio processing improvements, available in main branch now. They will be available in next version of LiTr (> 1.4.17)
