### ISSUE TITLE
Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference

### ISSUE THREAD

**Issue by dexter2019** [linkedin/LiTr#16]
Hello Team, 

 Thanks for the amazing library. 
However, while trying using the same I was facing an issue.

 E/TransformationJob: Transformation job error

 java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at android.media.MediaFormat.getInteger(MediaFormat.java:591)
        at com.linkedin.android.litr.utils.TranscoderUtils.getEstimatedTargetFileSize(TranscoderUtils.java:71)
        at com.linkedin.android.litr.TransformationJob.verifyAvailableDiskSpace(TransformationJob.java:147)
        at com.linkedin.android.litr.TransformationJob.transform(TransformationJob.java:93)
        at com.linkedin.android.litr.TransformationJob.run(TransformationJob.java:74)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

This is how I am trying to use it :

 MediaTransformer mediaTransformer = new MediaTransformer(c);

                TransformationListener transformationListener = new TransformationListener() {
                    @Override
                    public void onStarted(@NonNull String id) {

                        System.out.println("compress started");
                    }

                    @Override
                    public void onProgress(@NonNull String id, float progress) {

                    }

                    @Override
                    public void onCompleted(@NonNull String id, @Nullable List<TrackTransformationInfo> trackTransformationInfos) {

                        System.out.println("compress done");

                    }

                    @Override
                    public void onCancelled(@NonNull String id, @Nullable List<TrackTransformationInfo> trackTransformationInfos) {

                    }

                    @Override
                    public void onError(@NonNull String id, @Nullable Throwable cause, @Nullable List<TrackTransformationInfo> trackTransformationInfos) {

                    }
                };
                mediaTransformer.transform("abc",
                        Uri.fromFile(file),
                        cacheFile.getAbsolutePath(),
                        MediaFormat.createVideoFormat( "video/avc", 720,360),
                       MediaFormat.createAudioFormat("audio/mp4a-latm", 48000, 2),
                        transformationListener,
                        MediaTransformer.GRANULARITY_DEFAULT,
                        null);

as given in your Doc. Looking forward for some help, please.

**Comment by izzytwosheds** [comment]
Thank you for reporting this! We will definitely look into this. Which version of LiTr did this happen on? Does this happen with a specific video, or different videos? Would it be possible to get a copy of a video this happens on?

**Comment by dexter2019** [comment]
@izzytwosheds I am using com.linkedin.android.litr:litr:1.2.4. It is happening for all the videos.

I solved this using the process using the concept used in Litr Demo app. Like using Source Media, Target Media, Track Transformations and then using the Litr Transformer. 

I was using Moto G Android - marshmellow version

**Comment by izzytwosheds** [comment]
Ah, now I see. Looks like you had a target format with no bitrate. LiTr doesn't like that, because Android's encoder MediaCodec requires bitmap parameter. I will think of more defensive logic (like using source bitrate, maybe), but for now clients must specify desired bitrate. 

I will close this issue for now.
