### ISSUE TITLE
Transcode video without glfilter

### ISSUE THREAD

**Issue by Egorkansk** [linkedin/LiTr#17]
Hello friend!
I want to simple transcode video to another, and app throws ANR

What i am doing wrong? my code:

MediaTransformer mediaTransformer = new MediaTransformer(getApplicationContext());

MediaFormat format = MediaFormat.createVideoFormat("video/avc", 1280,720);
format.setInteger(MediaFormat.KEY_BIT_RATE, 2500000);
format.setInteger(MediaFormat.KEY_FRAME_RATE, 25);
format.setInteger(MediaFormat.KEY_I_FRAME_INTERVAL, 10);
format.setInteger(MediaFormat.KEY_COLOR_FORMAT, MediaCodecInfo.CodecCapabilities.COLOR_FormatSurface);

TransformationListener tl=new TransformationListener() {

@Override
public void onStarted(String id)
{
// TODO: Implement this method
}

@Override
public void onProgress(String id, float progress)
{
// TODO: Implement this method
}

@Override
public void onCompleted(String id, List<TrackTransformationInfo> trackTransformationInfos)
{
sm("ok");
}

@Override
public void onCancelled(String id, List<TrackTransformationInfo> trackTransformationInfos)
{
// TODO: Implement this method
}

@Override
public void onError(String id, Throwable cause, List<TrackTransformationInfo> trackTransformationInfos)
{
sm("error="+id);
}
};

Uri uri=Uri.parse(Environment.getExternalStorageDirectory()+"/vid.mp4");

mediaTransformer.transform("663600",
uri,
Environment.getExternalStorageDirectory()+"/vidos1.mp4",
format,
null,
tl,
MediaTransformer.GRANULARITY_DEFAULT,
null);

**Comment by izzytwosheds** [comment]
MediaFormat looks correct. Listener looks correct. 
Does your app have WRITE_EXTERNAL_STORAGE permission? 
Can you send a stack trace and a log?

**Comment by Egorkansk** [comment]
Thank you very much! I fogot write permission in manifest, now works!

**Comment by izzytwosheds** [comment]
Excellent! Good luck with your project! Let us know if you have any questions or suggestions.
