### ISSUE TITLE
Javadocs artefacts no longer being created as of 1.4.16

### ISSUE THREAD

**Issue by beeradmoore** [linkedin/LiTr#174]
I came across this issue while updating my Xamarin.Android [bindings](https://github.com/beeradmoore/Xam.Plugin.LinkedIn.LiTr) to test the update announced in #119. My local bindings were no longer working after jumping to 1.4.18. For reference the Xamarin binding project does not build this project from source but uses the published litr javadoc.jar, litr sources.jar and litr.aar files. So digging around into my build issues I found that:

As of [1.4.14](https://repo1.maven.org/maven2/com/linkedin/android/litr/litr/1.4.14/) litr-1.4.15-javadoc.jar was 316763 bytes
As of [1.4.15](https://repo1.maven.org/maven2/com/linkedin/android/litr/litr/1.4.15/) litr-1.4.15-javadoc.jar was 316642 bytes
As of [1.4.16](https://repo1.maven.org/maven2/com/linkedin/android/litr/litr/1.4.16/) litr-1.4.16-javadoc.jar was 261 bytes
As of [1.4.17](https://repo1.maven.org/maven2/com/linkedin/android/litr/litr/1.4.17/) litr-1.4.17-javadoc.jar was 261 bytes
As of [1.4.18](https://repo1.maven.org/maven2/com/linkedin/android/litr/litr/1.4.18/) litr-1.4.18-javadoc.jar was 261 bytes

1.4.15 predates the [only PR that I saw](https://github.com/linkedin/LiTr/commit/0b539c3e7e23d3c0e3d75df36404e4395f7a5a0b) that mentions javadocs.

I'm not a Java/Native Android dev so I am unsure what the problem is or how to fix it, just letting you know this has changed incase it was an accident. litr-filters seems to have javadocs enabled so I thought it was odd it disappeared from the main project.

**Comment by izzytwosheds** [comment]
Thanks for reporting this! This is odd, I will take a look. There were few changes to build parmeters, especially related to using Kotlin, but nothing directly related to Javadocs.

**Comment by izzytwosheds** [comment]
This is now fixed. The problem was with us adding Kotlin classes and javadoc tool not liking that. Fortunately, Google finally added proper javadoc support in AGP, which we are now using. You can try integrating the latest snapshot version. Let me know how that works.
