### ISSUE TITLE
How to trim a video, without transcoding?

### ISSUE THREAD

**Issue by pcm2a** [linkedin/LiTr#189]
This is probably not an issue and just my lack of following the documentation correctly. I'm looking to replace ffmpeg for two operations: trimming and transcoding. The transcoding was straight forward and works great. What I haven't figured out is how to trim a video without doing any transcoding? Just trimming a video should be real fast, where transcoding can be slow.

The MediaRange and TransformationOptions is self explanatory. What I haven't figured out is how to create a MediaFormat that tells it to be a direct copy without any transcoding. Any tips is appreciated, thanks!

**Comment by inwady** [comment]
Hello, you need to transcode a video for this action because the source of video is raw bytes.

**Comment by izzytwosheds** [comment]
It is possible to trim a video without transcoding it. Pass `null` for both target video and target audio formats along with `MediaRange`. Process will be fast (no transcoding), but actual trim positions won't likely match ones specified in `MediaRange`. This happens because we can only trim video at key frames, which are positioned every N seconds in video track.
You can try this in LiTr demo app - use first demo case "Transcode Video/Audio (GL Renderer)", set trim interval and do not select "Transcode" for video or audio tracks.

**Comment by pcm2a** [comment]
Thanks I have been looking into that today.

1. In the sample app, the trimming is fast and does work on some videos. Some it gives an error.

2. When I try to run this code separately, passing in null for both target formats, it always fails with an error.

```
E/d: Transformation job error
    java.lang.IllegalStateException: Failed to stop the muxer
        at android.media.MediaMuxer.nativeStop(Native Method)
        at android.media.MediaMuxer.stop(Unknown Source:7)
        at android.media.MediaMuxer.release(Unknown Source:5)
        at b9.b.release(MediaMuxerMediaTarget.java:149)
        at u8.d.g(TransformationJob.java:253)
        at u8.d.j(TransformationJob.java:117)
        at u8.d.run(TransformationJob.java:77)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

3.  Debugging the sample app, the transform method mentioned is not what is used. The sample app is using a different transform method that takes in a list of TrackTransforms. I haven't gotten this working in my app yet.

4. Not totally related, but k4l video trimmer has a trimming implementation that uses com.googlecode.mp4parser. It is super simple and takes in a file input, output, and the start and end trim times. So far it has worked on every file I've thrown at it.

**Comment by izzytwosheds** [comment]
Thank you for the suggestion! I will take a look at k4l. 
I will also take a look why simple transform method with two `null` target formats is not working, sounds like a bug.

**Comment by pcm2a** [comment]
Did you determine if this is a bug? I have tried to copy over the MediaTransformer class to see if the bug was in there but it doesn't appear to be.

**Comment by pcm2a** [comment]
Closing this. I spent some time debugging the library to find the issue. The issue was not with the library but with my MediaRange. I was passing in milliseconds and that was crashing it. Converted milliseconds to microseconds and it works fine.

**Comment by izzytwosheds** [comment]
Ok, that explains it. LiTr was probably not finding any frames within that range.
