### ISSUE TITLE
Much higher bitrate of transcoding output than configuration

### ISSUE THREAD

**Issue by piaoliangkb** [linkedin/LiTr#192]
Hi, I used litr-demo for transcoding H.264 videos. For example, when setting the target bitrate to 0.215M for a less-complexity 1080P video, bitrate of output video is always much higher than that (4M), which is larger than the origin video (about 0.43M). Even if I modified the encoding `MediaFormat` by setting `KEY_MAX_BIT_RATE` equals to the target bitrate.

I also test the CBR mode by setting `KEY_BIT_RATE_MODE` to 2 but the results keep the same. Thus I wonder are there any constraints internally LiTr on the minimum video bitrate? 

The chipset of the testing device is Snapdragon 865 and the Android SDK version is 29. Appreciate your awesome framework and looking forward to your reply!

**Comment by piaoliangkb** [comment]
Thanks for your quick reply! The behavior is really strange cause the bitrate option does not work. Don't know if anyone has found this problem previously?

**Comment by piaoliangkb** [comment]
Finally I found why this happened: taking videos in mkv format as input will let LiTr parse video fps incorrectly. The `KEY_I_FRAME_INTERVAL` parameter depends on video fps thus can't work well.

A concrete case: fps = -1 and i_frame_interval = 5 makes my 5-second video full of I-frame, thus the bitrate of the output video is much larger than expected.

**Comment by izzytwosheds** [comment]
That is a nice find! Thank you for sharing it, I will remember it in case someone else has a similar issue.
