### ISSUE TITLE
Muting a video

### ISSUE THREAD

**Issue by Noloxs** [linkedin/LiTr#196]
Is there an official or easy way to mute a video during transcoding?

I haven't been able to find any example through search, and I can't seem to find a "mute video" example in the demo app. I have been able to do it in the TranscodeVideoGl example by manually not including all the present audio tracks available, that just doesn't seem like the right way to do it in the mute video scenario.

Hope someone can point me in the right direction.

**Comment by izzytwosheds** [comment]
There is no "official" way per se. With current LiTr functionality there are two ways to "mute" a video:
 - use `transform(List<TrackTransform>)` method to pick only non-audio tracks from source video
 - use `VolumeFilter` audio filter to set the volume to 0

Which way you use depends on your use case (for example, what consumer of transcoded video would expect) I usually use the first way to remove audio track entirely.

**Comment by Noloxs** [comment]
Hi.
Thanks a lot for the quick response.

I have been trying your suggestion of removing the audio tracks, as we want the video to not have the data.
However I just can't seem to get it to work.
Basically, when I remove the audio track, the transcoding completes successfully, but the result file empty.

The way I implemented it, to test it, was taking the [transform method from MediaTransformer](https://github.com/linkedin/LiTr/blob/c74f2703217d200730bc177f69aff66612343e44/litr/src/main/java/com/linkedin/android/litr/MediaTransformer.java#L142) and adding a mute parameter to it (boolean).
Then if true triggers a continue while going through the [different tracks of the video file] (https://github.com/linkedin/LiTr/blob/c74f2703217d200730bc177f69aff66612343e44/litr/src/main/java/com/linkedin/android/litr/MediaTransformer.java#L196) where it finds an audio track.

Here is the configuration I used if that helps:
 ```
MediaFormat targetVideoFormat = MediaFormat.createVideoFormat(
                    MediaFormat.MIMETYPE_VIDEO_AVC,
                    scaledVideoSize.getWidth(),
                    scaledVideoSize.getHeight());
            targetVideoFormat.setInteger(MediaFormat.KEY_BIT_RATE, getBitrate(recipientSize));
            targetVideoFormat.setInteger(MediaFormat.KEY_FRAME_RATE, 30);
            targetVideoFormat.setInteger(MediaFormat.KEY_I_FRAME_INTERVAL, 99); //This is in seconds and so we only have first keyframe

            MediaFormat audioFormat = MediaFormat.createAudioFormat(MediaFormat.MIMETYPE_AUDIO_MPEG, 44100, 2);
            audioFormat.setInteger(MediaFormat.KEY_BIT_RATE, 96000);

            MediaRange mediaRange = new MediaRange(
                    TimeUnit.MILLISECONDS.toMicros(videoDelivery.getFromTimeMs()),
                    TimeUnit.MILLISECONDS.toMicros(videoDelivery.getToTimeMs()));

            TransformationOptions transformationOptions = new TransformationOptions.Builder()
                    .setSourceMediaRange(mediaRange)
                    .build();

            MediaTransformer mediaTransformer = new MediaTransformer(MainApplication.getAppContext());
            mediaTransformer.transform(
                    String.valueOf(videoDelivery.getModelId().getId()),
                    mediaFromMediaDelivery.getUriPath(),
                    transcodedTemp.getAbsolutePath(),
                    targetVideoFormat,
                    null,
                    new TransformationListener() {
                        @Override
                        public void onStarted(@NonNull String id) {}

                        @Override
                        public void onProgress(@NonNull String id, float progress) {}

                        @Override
                        public void onCompleted(@NonNull String id, @Nullable List<TrackTransformationInfo> trackTransformationInfos) {}

                        @Override
                        public void onCancelled(@NonNull String id, @Nullable List<TrackTransformationInfo> trackTransformationInfos) {}

                        @Override
                        public void onError(@NonNull String id, @Nullable Throwable cause, @Nullable List<TrackTransformationInfo> trackTransformationInfos) { }
                    },
                    transformationOptions);
```
Can you point be in the direction towards what the issue might be, or share an example on how else to mute the video?

Is there any thoughts on adding a mute feature in the future?

**Comment by izzytwosheds** [comment]
I see what is going on. You are using a simpler `transform` API that takes in paths and `TransformationOptions`. You have to use a different `transform` API that takes a `List<TrackTransform>`. That will let you select tracks from source video and have per-track transcoding options. Which means you can select only video track(s) and not audio track(s), which will produce a transcoded video with no audio. 
`TransformationPresenter.startTransformation` method in demo app shows how tracks can be included/excluded.
I am actually considering also adding a flag in `TransformationOptions` to remove audio, thank you for the inspiration!

**Comment by EzequielAdrianM** [comment]
I didn't feel like adding 4mb extra to my app importing com.linkedin.android.litr:litr-filters:1.5.2 just for Audio filtering, so I converted [VolumeFilter.kt](https://github.com/linkedin/LiTr/blob/main/litr-filters/src/main/java/com/linkedin/android/litr/filter/audio/VolumeFilter.kt) kotlin code to java and added that simple class to my app and it worked, producing a silenced video. Here is the result:

```
import android.media.MediaFormat;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.linkedin.android.litr.codec.Frame;
import com.linkedin.android.litr.filter.BufferFilter;

import java.nio.ShortBuffer;

/**
 * An audio filter that changes the audio track volume:
 * - 1 will keep the volume "as is"
 * - 0 will silence the track
 * - value <1 will lower the volume
 * - value >1 will increase it. One has to be careful with these, since large values may result in distortion.
 */
public class LiTrVolumeFilter implements BufferFilter {
    double volume;
    double base = 10.0;
    public LiTrVolumeFilter(double volume) {
        this.volume = volume;
    }

    @Override
    public void apply(@NonNull Frame frame) {
        ShortBuffer buffer = frame.buffer.asShortBuffer();
        float sampleCount = frame.bufferInfo.size / 2;
        for(int i=0; i<sampleCount; i++) {
            // replace sample at index with volume adjusted value
            buffer.put(i, (short)(buffer.get(i) * (Math.pow(base, volume) -1) / (base-1)));
        }

    }

    @Override
    public void init(@Nullable MediaFormat mediaFormat) {

    }
}
```

Implemented like this:

```
TransformationOptions transformationOptions = new TransformationOptions.Builder().setAudioFilters(Collections.singletonList(new LiTrVolumeFilter(0))).build();
```

Any way, it would be nice if we could just call a flag for removing the audio channel. Cheers!

**Comment by inwady** [comment]
Hello, 

how I understand the second solution is worse than first, which uses additional encoder and decoder (more risky on budget devices)?

Thank you for the great example.

**Comment by izzytwosheds** [comment]
@inwady great point! It didn't occur to me.

**Comment by izzytwosheds** [comment]
@EzequielAdrianM If you are using code shrinker/obfuscator (like proguard) it should remove all unused code.

**Comment by Noloxs** [comment]
I got muting to work with the simple transform API with only a few changes. The issue I was experiencing before was because I hadn't seen the track count in the constructor of the MediaTarget, so it expected 2 but was only given 1.

So the test code I made was based on:

- Making a class that extended MediaTransformer
- Copying the simple transform method
- Adding a mute parameter (Would be nice if that was a flag in TransformationOptions as you suggested @izzytwosheds)
- Adding a method to calculate enabledTracks (Used that value in the MediaTarget constructer and trackTransforms list size)
- Adding an "else if" when going through all the tracks that just continues when it sees an audio track and mute is true

@izzytwosheds Do you know if there is any plans for an official implementation of mute? as this would still be preferable to my home brewed solution

**Comment by izzytwosheds** [comment]
So official implementation of muting a video already exists (we use it internally) - muting is done by using `TrackTransform` API and excluding audio tracks from the target. I agree that it might get a bit cumbersome to use that API just to remove audio. So now flag is added to `TransformationOptions`, should make things easier. Let me know how it works out for you.

**Comment by EzequielAdrianM** [comment]
When release? Trying to build that snapshot at jitpack but failed. [https://jitpack.io/com/github/linkedin/LiTr/df3252f89b/build.log](https://jitpack.io/com/github/linkedin/LiTr/df3252f89b/build.log)

**Comment by izzytwosheds** [comment]
I will quickly look at another reported issue, and release the new version after that fix.
