### ISSUE TITLE
MarshallingTransformationListener onError callback is not invoked 

### ISSUE THREAD

**Issue by simekadam** [linkedin/LiTr#197]
Hi, we have recently succesfully deployed LiTr to production at Strava. So first of all kudos for your great work. 
However we have also started to receive some feedback about failing processing on certain devices. 
Unfortunately it bypasses our error tracking and even error handling in the UI. 
I have found the issue to be the same as someone already mentioned in [here](https://github.com/linkedin/LiTr/issues/79#issuecomment-888942997) 

The `MarshallingTransformationListeneronError` callback is not invoked [here](https://github.com/linkedin/LiTr/blob/571b1c5b6c4d1c7d613a1503a66256f316a968d2/litr/src/main/java/com/linkedin/android/litr/TransformationJob.java#L129) because `TransformationJob.release(false)` hangs in my case in `VideoTrackTranscoder.stop()`

I can open a PR and flip the order of execution if you think it would be accepted.

**Comment by izzytwosheds** [comment]
Thank you for using LiTr! That is so awesome to hear! 

By all means, create a PR. I will be happy to review it. One of reasons making LiTr open source was to make it possible for LiTr community benefit from each other's work. Has worked out pretty well so far.

**Comment by izzytwosheds** [comment]
You fix is in latest release 1.5.2. Thank you!

**Comment by izzytwosheds** [comment]
Would you be ok with providing a bit more details on how you guys use LiTr. We can do that over email or LinkedIn messaging. My email is is izzat at linkedin.com.

**Comment by simekadam** [comment]
Thanks! I have just bumped the version on our end. 
And sure. Happy to send you over some details around how are we using it.
