### ISSUE TITLE
Maybe a memory leak in audio-process.cpp

### ISSUE THREAD

**Issue by kaitian521** [linkedin/LiTr#201]
`
auto resamplerInputBuffer = new float[outputChannelCount];
auto resamplerOutputBuffer = new float[outputChannelCount];
`
This two float buffer can be allocated just by once， for example,  can be inited in `Java_com_linkedin_android_litr_render_OboeAudioProcessor_initProcessor`
and uninit in 
`Java_com_linkedin_android_litr_render_OboeAudioProcessor_releaseProcessor`
to avoid multiple memory junks

**Comment by izzytwosheds** [comment]
Good call, I will look into this. Thank you!
