### ISSUE TITLE
Audio sample rate change, number of channel change

### ISSUE THREAD

**Issue by bvananda2** [linkedin/LiTr#205]
When we transcode audio
1. Change sample rate
2. Change number of channels (mono <-> stereo )

Audio is not proper

Mono <-> Stereo change is present here
https://github.com/ypresto/android-transcoder/blob/master/lib/src/main/java/net/ypresto/androidtranscoder/engine/AudioChannel.java

**Comment by izzytwosheds** [comment]
Can you provide more details? Are you changing stereo to mono or reversed? Does audio sound corrupted?

I am having hard time reproducing it.

**Comment by izzytwosheds** [comment]
Closing this for now. Feel free to reopen it if you see this problem again.
