### ISSUE TITLE
Convert audio to video

### ISSUE THREAD

**Issue by FirstVoyager** [linkedin/LiTr#207]
I have two questions:
1. Can I convert Audio files to Video files?
2. Can I add background to the Video file?

**Comment by izzytwosheds** [comment]
1. Yes
2. Yes

You will need two handy classes LiTr offers: `MockVideoMediaSource` and `PassthroughDecoder`. First will produce empty video frames, and second will pretend to decode them. To render a bitmap on top you can use `BitmapOverlayFilter` from `litr-filters`, or ` FrameSequenceAnimationOverlayFilter` if you want to change backgrounds. There is `TransformationPresenter.createEmptyVideo` method in demo app that should get you started.

**Comment by izzytwosheds** [comment]
Closing this issue for now. Feel free to re-open it if this doesn't work.
