### ISSUE TITLE
Rotation stuck at 0 progress for some specific videos

### ISSUE THREAD

**Issue by novachevskyi** [linkedin/LiTr#210]
**Steps:**
1. Open the Demo app and go to "Free Transform Video (GL Renderer)"
2. Pick a previously downloaded [video](https://drive.google.com/file/d/1-k1QqLecVHEDr4NZ0F-cvvYxKrPgZ0v4/view?usp=sharing).
3. Select 0 rotation degrees.
4. Tap on Transcode button and observe progress stuck at 0.

**Prerequisites:**
The initial rotation of the source file is 90 degrees. The goal of the conversion is to make a few video files have the same configuration to be able to merge them sequentially with [mp4parser](https://github.com/sannies/mp4parser) lib. The same happens when applying a render filter to resize the same video, probably issue is related to size change.

WIll appreciate any help or advice on this.

**Comment by izzytwosheds** [comment]
Thank you for reporting this. I will take a look at it. Thank you for providing a sample video!

**Comment by izzytwosheds** [comment]
Again, thank you for reporting this and for sample video. It was very interesting (it had bunch of metadata tracks embedded) which helped fix bunch of bugs. Latest master should work now. Let me know if works for you.

**Comment by novachevskyi** [comment]
@izzytwosheds Thanks for the quick fix! It works for me now. However, trim still has an issue. Reported [here](https://github.com/linkedin/LiTr/issues/216). Will appreciate if you can have look at it as well.
