### ISSUE TITLE
is not support mov to mp4?

### ISSUE THREAD

**Issue by king-ma1993** [linkedin/LiTr#215]
is not support mov to mp4?

**Comment by izzytwosheds** [comment]
If mov file is playable on your device, LiTr should be able to transcode it to MP4.

**Comment by king-ma1993** [comment]
> If mov file is playable on your device, LiTr should be able to transcode it to MP4.

it is ok in my device photo album,but is wrong is Litr.
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/77381352/189259125-ea7032ce-0872-4fb0-9245-8d713c6027a7.png">

**Comment by izzytwosheds** [comment]
Looks like you are trying to encode audio into "audio/raw" which I don't think is supported. Try encoding into `audio/mp4a-latm`, that works with MP4 video.

**Comment by king-ma1993** [comment]
> Looks like you are trying to encode audio into "audio/raw" which I don't think is supported. Try encoding into `audio/mp4a-latm`, that works with MP4 video.

my input is "audio/raw" and encoding into audio/mp4a-latm,but didn't work well,the MP4 video is no voice

**Comment by izzytwosheds** [comment]
interesting. Would it be possible to send me that source video?

**Comment by izzytwosheds** [comment]
izzat @ linkedin.com

**Comment by Noloxs** [comment]
I get the following when attempting to transcode a MOV videos.
Would more videos that cause the issue be helpful to you @izzytwosheds?

```
E  Unsupported mime 'audio/raw'
E  Transformation job error
java.lang.IllegalStateException: Failed to add the track to the muxer
   at android.media.MediaMuxer.nativeAddTrack(Native Method)
   at android.media.MediaMuxer.addTrack(MediaMuxer.java:661)
   at com.linkedin.android.litr.io.MediaMuxerMediaTarget.addTrack(MediaMuxerMediaTarget.java:116)
   at com.linkedin.android.litr.transcoder.VideoTrackTranscoder.writeEncodedOutputFrame(VideoTrackTranscoder.java:285)
   at com.linkedin.android.litr.transcoder.VideoTrackTranscoder.processNextFrame(VideoTrackTranscoder.java:141)
   at com.linkedin.android.litr.TransformationJob.processNextFrame(TransformationJob.java:211)
   at com.linkedin.android.litr.TransformationJob.transform(TransformationJob.java:108)
   at com.linkedin.android.litr.TransformationJob.run(TransformationJob.java:77)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
   at java.util.concurrent.FutureTask.run(FutureTask.java:264)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
   at java.lang.Thread.run(Thread.java:1012)
```

**Comment by izzytwosheds** [comment]
Yes, sample video would be very helpful.

So from the stack trace you sent it looks like MOV file has an audio track in `audio/raw` format and target audio format is most probably set to `null`, which means that audio track must be copied with no modifications. However, MP4 container is not liking it, it usually wants audio to be compressed into `mp4a-latm` format. I will look into enforcing this in LiTr code. Meanwhile, you can use a workaround and pass in target audio format yourself, which should fix this problem.

**Comment by Noloxs** [comment]
Okay, I will try to find a set of shareable videos and send them to you (Just the mail mentioned above, right?)

As far as I can tell I should already be setting the target audio format.

```
MediaFormat targetAudioFormat = MediaFormat.createAudioFormat(MediaFormat.MIMETYPE_AUDIO_AAC, 44100, 2);
targetAudioFormat.setInteger(MediaFormat.KEY_BIT_RATE, 96000);

...

 MediaTransformer mediaTransformer = new MediaTransformer(MainApplication.getAppContext());
            mediaTransformer.transform(
                    String.valueOf(videoDelivery.getModelId().getId()),
                    mediaFromMediaDelivery.getUriPath(),
                    transcodedTemp.getAbsolutePath(),
                    targetVideoFormat,
                    targetAudioFormat,
                    new TransformationListener() {
                    ...
```

**Comment by Noloxs** [comment]
I have added you to a Google drive folder with a couple of videos that I have confirmed also produces the error in the demo app.

Let me know if you can't access them or would like them some other way.

**Comment by izzytwosheds** [comment]
@Noloxs Which email did you use for google drive? I don't see the shared folder. Can you share it with ibahadirov at linkedin.com ?

**Comment by Noloxs** [comment]
> izzat @ linkedin.com

I had used this one.
Replaced it with the new email.

You should have access now

**Comment by izzytwosheds** [comment]
@Noloxs thank you for sample videos! I see what the problem is now. MOV file has audio track in uncompressed format, so when LiTr tries to encode/write it "as is", attempt to find an encoder fails since there is no encoding into uncompressed format. I will add compression enforcement in the code. For now you can use a workaround by setting explicit target audio format - with explicit `audio/mp4a-latm` mime type and bitrate. I tried this and it works.
