### ISSUE TITLE
Trim issue for the specific video

### ISSUE THREAD

**Issue by novachevskyi** [linkedin/LiTr#216]
**Steps:**

1. Open the Demo app and go to "Transcode Video/Audio (GL Renderer)"
2. Pick a previously downloaded [video](https://drive.google.com/file/d/1-k1QqLecVHEDr4NZ0F-cvvYxKrPgZ0v4/view?usp=sharing).
3. Enable trim and cut the half to ~5 secs.
4. Tap on Transcode button and observe that resulted video still has 10 secs length, but playback stuck after reaching 5 secs.

**Comment by izzytwosheds** [comment]
That is an interesting fid. I will take a look.

**Comment by novachevskyi** [comment]
Hi @izzytwosheds ! Curios if you have the possible solution in your mind. Let me know if you need any help to debug the issue or something.

**Comment by izzytwosheds** [comment]
I am planning to look into this issue on Friday. 
I noticed an interesting thing while debugging it. When I select only one metadata track + video + audio tracks trimming works fine. When selecting multiple tracks, it doesn't. For some reason it never reaches the end of one of metadata tracks, so track transcoder never finishes it work.

**Comment by novachevskyi** [comment]
@izzytwosheds wondering if you had a chance to take a look at the issue. I'm trying to integrate the lib into the project but at this point is blocked since trimming functionality is crucial.

Is it possible by any chance to make some logic in my client app to programmatically select a single metadata track and ignore other ones? What could be the possible criteria for tracks to ignore if that's the case? 

Appreciate your help on this.

**Comment by izzytwosheds** [comment]
Didn't get a chance to look into this issue, it is still sitting in my backlog. Sorry about that. 
You can write a workaround in your app for now. Use `TrackTransform` api to ignore all non-AV tracks. `TransformationPresenter.startTransformation()` method should be a good start example, it selectively adds tracks to the target video. Adding a "removeMetadata` flag to `TransformationOptions` is a neat idea, I will add it.

**Comment by izzytwosheds** [comment]
Excellent! I will still look into fixing this bug, it is still a very legitimate bug.

**Comment by izzytwosheds** [comment]
Well, this was a tricky bug and took a while to fix. Thank you for catching it and providing a video that allowed reproducing it. Bugfix will be included in the next release.
