### ISSUE TITLE
Are there plans to support ffmpeg?

### ISSUE THREAD

**Issue by king-ma1993** [linkedin/LiTr#217]
Are there plans to support ffmpeg?

**Comment by izzytwosheds** [comment]
Not really. LiTr is meant to be a hardware-accelerated limited functionality replacement of ffmpeg. It is possible to use parts of ffmpeg to extend LiTr functionality - for example, to write a custom decoder/encoder/parser/etc. But this is not something we are planning on doing anytime soon.
