### ISSUE TITLE
Not respecting rotation value 

### ISSUE THREAD

**Issue by SolidScorpion** [linkedin/LiTr#219]
First and foremost thanks for awesome library. While scary at first, but example project provides in depth instructions how to use everything.

My use case is simple - user selects a video and then I suggest compressing options that can be used before uploading video file to backend.

We encountered issues with compressing videos from SM-G920F ( Samsung S6 ) running Android 7.0. When user selects a vertical video from device and library is used to compress video (even without changing video resolution) resulting video is rotated 90 degrees. I double checked and `MediaFormat.KEY_ROTATION` is returning 90 on source video.

I first though that's the issue with my code but then I built sample app provided in this repo and ran it on phone in question. Selected first option `Transcode Video/Audio (GL Renderer)` -> selected vertical video from device -> choose transcode option on video track. Regardless of resolution I choose (even when using same width/height as in source video) after transcoding resulting video is horizontal 

[Here](https://drive.google.com/drive/folders/1sBFKCPRwou0q9iRgD0fpCddEBHRDYkmz?usp=sharing) is link for videos taken with that phone (horizontal and vertical) plus resulting video after compression.

All other phones I tested with Pixel4A Android 13, Samsung S9+ Android 10, Samsung S9 Android 9, Samsung A71 Android 12, Samsung A50 Android 10, Huawei P20 Android 10 they work properly

Is it something device specific? Can you push me in correct direction on what can be done from my side ?

**Comment by izzytwosheds** [comment]
Happy you are enjoying LiTr!
Which `tranform` method are you using? What is your target `MediaFormat`? I will try to reproduce this issue on my end.

**Comment by SolidScorpion** [comment]
I'm using following method of `MediaTransformer` class

```
 public void transform(@NonNull String requestId,
                          List<TrackTransform> trackTransforms,
                          @NonNull TransformationListener listener,
                          @IntRange(from = GRANULARITY_NONE) int granularity)
```

This is how I construct target media format video track:

```
    private fun createVideoMediaFormat(videoTrack: VideoTrackFormat): MediaFormat {
        return MediaFormat().apply {
            setString(MediaFormat.KEY_MIME, MediaFormat.MIMETYPE_VIDEO_AVC)
            setInteger(MediaFormat.KEY_WIDTH, videoTrack.width)
            setInteger(MediaFormat.KEY_HEIGHT, videoTrack.height)
            setInteger(MediaFormat.KEY_BIT_RATE, videoTrack.bitrate)
            setInteger(MediaFormat.KEY_I_FRAME_INTERVAL, videoTrack.keyFrameInterval)
            setInteger(MediaFormat.KEY_FRAME_RATE, videoTrack.frameRate)
            setLong(MediaFormat.KEY_DURATION, videoTrack.duration)
            setInteger(MediaFormat.KEY_ROTATION, videoTrack.rotation)
        }
    }
```

`VideoTrackFormat` is basically a copy from your sample project.

We are not aiming to be video production app, therefore we provide limited set of resolutions. This is how we map Video track according to user selected option

```
    private fun mapMediaTrackFormat(
        track: MediaTrackFormat,
        option: VideoCompressionOption
    ) = when (track) {
        is AudioTrackFormat -> track.copy(bitrate = DEFAULT_AUDIO_BITRATE) // we modify only audio quality for audio tracks
        is GenericTrack -> track
        is VideoTrackFormat -> {
            when (option) {
                VideoCompressionOption.ORIGINAL -> track.copy(bitrate = option.bitrate) // keep resolution, angle, etc. just modify bitrate
                else -> track.copy(
                    width = option.width,
                    height = option.height,
                    bitrate = option.bitrate,
                    rotation = videoRotation(option, track.isVertical)
                )
            }.copy(keyFrameInterval = DEFAULT_KEY_FRAME_INTERVAL)
        }
    }

    private fun videoRotation(option: VideoCompressionOption, isVideoVertical: Boolean): Int {
        val destinationIsVertical = option.height > option.width
        var rotation = 0
        if (isVideoVertical) {
            if (!destinationIsVertical) rotation = 90 // source is vertical, destination resolution is not, so rotate it
        } else {
            if (destinationIsVertical) rotation = 90 // source is horizontal, destination resolution is not, so rotate it
        }
        return rotation
    }
```

I consider source video vertical via following condition
```
    val isVertical: Boolean
        get() = height > width || rotation > 0
```

**Comment by izzytwosheds** [comment]
Rotation on the video you sent me is `-90`, which I think would not play well with `rotation > 0` logic.

**Comment by izzytwosheds** [comment]
The logic I use to downscale a video just reduces the smallest dimension (AKA resolution) to desired value, adjusts larger dimension to keep aspect ratio and maintains original orientation. Works pretty well.

**Comment by SolidScorpion** [comment]
> Rotation on the video you sent me is -90, which I think would not play well with rotation > 0 logic.

Fair enough, but sample project does not modify rotation and yet if video is transcoded with it, it's flipped as well horizontally as well?  Can you please point me where should I take a look in sample project's code?

**Comment by SolidScorpion** [comment]
Also I double checked rotation value.
I tried both methods using 
```
val mediaMetadataRetriever = MediaMetadataRetriever()
mediaMetadataRetriever.setDataSource(context, uri)
mediaMetadataRetriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_ROTATION)
```
And via 
```
 val mediaExtractor = MediaExtractor()
 mediaExtractor.setDataSource(context, uri, null)
val mediaFormat = mediaExtractor.getTrackFormat(trackIndex)
mediaFormat.getInteger(MediaFormat.KEY_ROTATION)
```
Both return 90?

**Comment by izzytwosheds** [comment]
Interesting. ffprobe is showing -90
I will debug on my end

**Comment by izzytwosheds** [comment]
I tried with LiTr demo app, it works fine. I think there is some corner case your rotation calculation is not catching.

**Comment by izzytwosheds** [comment]
Can you compare final width, height and rotation values that make up a target media format in your logic? I wonder if width and height are getting messed up.

**Comment by SolidScorpion** [comment]
Thanks for taking your time to look into it!

However as I already pointed out we moved our code out of the equation, there is no rotation logic. I'm not using any of our code. Issue is reproducible when using Samsung S6 SM-G920F with sample LiTr application provided in this repository

[Please take a look at sample videos](https://drive.google.com/drive/folders/1bLwPc59VU3Rf_BxDiKZ41-0DePB8cqVJ?usp=sharing)

We connected phone in question and cloned LiTr project from github using Android Studio. In provided video you can see we are doing fresh install of LiTr sample project from github on Samsung S6. Then we record vertical video and go back to LiTr app. Select Transcoding option, select freshly recorded video, input same width and height as in original video file and click transcode. Resulting video is flipped. There's no code from our side - only LiTr project code without any modifications (fresh pull and install)

I do think this is device specific?

**Comment by izzytwosheds** [comment]
I tried this on my Pixel 3 and transcoded video is portrait. So the problem here seems to be device related. 
From your video (thank you for providing them!) I noticed that width and height of target video get switched - 1920w x 1080w becomes 1080h x 1920w, while rotation of 90 is preserved by LiTr. So you end up with portrait resolution video which is displayed with 90 degree rotation, which makes it landscape. 

My guess is that this is happening because Samsung Galaxy S6 media stack is trying to be clever and actually change the video resolution to match desired orientation. 

Let's try something. Can you try to comment out line 748 in `TransformationPresenter` in LiTr demo app and try again on S6? Let's see if not setting rotation on a track metadata will help.

**Comment by SolidScorpion** [comment]
Thank you so much for taking your time. We decided to drop support for android 6 and this device along with it. 
I'm closing the issue so that it doesn't mess with repo stats :)
