### ISSUE TITLE
TransformationListener.onProgress() returns odd values

### ISSUE THREAD

**Issue by NLLAPPS** [linkedin/LiTr#223]
Hi, https://github.com/linkedin/LiTr/blob/main/litr/src/main/java/com/linkedin/android/litr/TransformationListener.java says that onProgress()  values are from 0 to 1, with client specified granularity.

But I get weird values unless  extraction start from 0. Am I doing something wrong?

For example, for MediaRange(start:20062000, end:50062000) with MediaTransformer.GRANULARITY_DEFAULT
I get below values when I try to extract a selection from 64kbps m4a audio that is 2minutes and 35 seconds long

first one is progress: 0.66948146 and last one is progress: 1.6686726

If i start from the beginning then values are in expected range.
For example, for MediaRange(start:0, end:30000000) with MediaTransformer.GRANULARITY_DEFAULT
I get below values when I try to extract a selection from 64kbps m4a audio that is 2minutes and 35 seconds long

first one is progress: 0.0038699333 and last one is progress: 0.9999653

**Comment by izzytwosheds** [comment]
Good find, I will look into this. Thank you!

**Comment by emrisb** [comment]
Hi @izzytwosheds, I have this issue as well, when will the next version be released or any workaround suggestion for now?

**Comment by izzytwosheds** [comment]
I will release a new version soon. Working on another bugfix which I am hoping to get into next release, should not take long.

**Comment by izzytwosheds** [comment]
New version (1.5.4) is released.
