### ISSUE TITLE
Migration to Jetpack compose in Demo examples

### ISSUE THREAD

**Issue by pawaom** [linkedin/LiTr#241]
Migration to Jetpack compose

Do you plan to migrate to jetpack compose, in Demo examples, you have used databinding and the old xml code, the recommended way by google is to use jetpack compose in future, how soon can we expect to migrate to jetpack compose.

**Comment by izzytwosheds** [comment]
Wasn't really planning on it. I might do it as a side project, but it is not a priority for now.
