### ISSUE TITLE
Transcode HDR video to HDR

### ISSUE THREAD

**Issue by joechan-cq** [linkedin/LiTr#252]
I found that if i transcode the hdr video on the device which supports the hdr-video-capture, the output-video would be sdr, its color was washed out.
Is it possible that transcoding the hdr video to hdr?

`Original Video`
![image](https://user-images.githubusercontent.com/9456005/217987111-d4b08efa-bc93-470a-9ca0-52328bb1382a.png)
![image](https://user-images.githubusercontent.com/9456005/217987234-4fa230da-408b-41ca-b01e-182fb776a157.png)

`Output Video`
![image](https://user-images.githubusercontent.com/9456005/217987182-660f1fbf-7fa6-4855-9005-55541d1abc24.png)
![image](https://user-images.githubusercontent.com/9456005/217987274-d549f022-b3fc-4ca4-a8a9-9acef6ba48c1.png)

**Comment by joechan-cq** [comment]
Set ColorStandard、ColorTransfer、ColorRange to outputFormat for encoder, then it will support the hdr video.

```
                if (inputFormat.containsKey(MediaFormat.KEY_COLOR_STANDARD)) {
                    mVideoOutputFormat.setInteger(MediaFormat.KEY_COLOR_STANDARD,
                            inputFormat.getInteger(MediaFormat.KEY_COLOR_STANDARD));
                }
                if (inputFormat.containsKey(MediaFormat.KEY_COLOR_TRANSFER)) {
                    mVideoOutputFormat.setInteger(MediaFormat.KEY_COLOR_TRANSFER,
                            inputFormat.getInteger(MediaFormat.KEY_COLOR_TRANSFER));
                }
                if (inputFormat.containsKey(MediaFormat.KEY_COLOR_RANGE)) {
                    mVideoOutputFormat.setInteger(MediaFormat.KEY_COLOR_RANGE,
                            inputFormat.getInteger(MediaFormat.KEY_COLOR_RANGE));
                }
```

**Comment by izzytwosheds** [comment]
Apologies for not responding sooner! Thank you for figuring this out and sharing it with everyone!
