### ISSUE TITLE
Loss of video audio

### ISSUE THREAD

**Issue by anvanvo** [linkedin/LiTr#258]
I am mixing mp3 audio into mp4 video, but the resulting old audio of the video is lost

**Comment by izzytwosheds** [comment]
Can you provide a code sample? Are you adding a new track or mixing audio in using `AudioOverlayFilter`?

**Comment by anvanvo** [comment]
I am using lite-demo available and got error field like above, Feature Mux Video And Audio Track

**Comment by anvanvo** [comment]
Do you have a sample code for muxing audio into video while keeping the old audiotrack?

**Comment by izzytwosheds** [comment]
Very first demo (Transcode Video/Audio GL) has a capability to apply audio overlay. That does what you need.

**Comment by anvanvo** [comment]
I got it, thanks for your help!

**Comment by izzytwosheds** [comment]
Awesome! Let us know if you need more help.
