### ISSUE TITLE
Can you provide us with a simple app to add watermark on vedio (branding like tiktok).

### ISSUE THREAD

**Issue by vaibhavvats1000** [linkedin/LiTr#27]

**Comment by izzytwosheds** [comment]
Sure, I will look into this. So you need to change video resolution/bitrate?

Note: Current demo app does that, but uses more complex API.

**Comment by vaibhavvats1000** [comment]
Actually I need to add a watermark/logo on the saved video. No, I don't want to change the video resolution as per.

**Comment by izzytwosheds** [comment]
I added a new "Video Watermark" demo case to demo app. The method that you need to look at is `TransformationPresenter.applyWatermark`
