### ISSUE TITLE
Create thumbnail functionality

### ISSUE THREAD

**Issue by jdivins** [linkedin/LiTr#28]
Maybe I haven't searched enought, but I think there isn't any method to get a thumbnail of the transcoded vídeo?
If this functionality is not present, do you think you are going to add this?

Another question:
I have been trying the demo app and if I choose to transcode the sound of a video, I can't play the final result and the progress bar doesn't go to 100%
![image](https://user-images.githubusercontent.com/1632358/83358857-ad77cf00-a376-11ea-99d5-fb4e6597490a.png)

Finally:
Do you know which different Android devices have tried the transcoding with success transcoding?

Thanks a lot

**Comment by izzytwosheds** [comment]
Thumbnail extraction can be done using `MetadataRetriever.getFrameAtTime` or `MetadataRetriever.getFrameAtIndex`: https://developer.android.com/reference/android/media/MediaMetadataRetriever#getFrameAtTime(long)

I will look into auto transcoding failure. Are you getting this with every video or just particular one? Which device are you running on? (I see it is a Samsung, I don't know which one)

**Comment by jdivins** [comment]
Thank you @izzytwosheds 
It's a tablet Samsung SM-T700 and the error is with every video recorded from tablet camera.

**Comment by izzytwosheds** [comment]
Can you try transcoding using very first menu item in demo app? (simple transcode, no rotation) Let me know if it works. 

Can you also capture and send me the adb logcat log for failure(s)?

**Comment by izzytwosheds** [comment]
@jdivins Can you try with latest version (1.4.6) or latest master? I submitted a fix for a very similar issue.

**Comment by izzytwosheds** [comment]
Closing the issue for now. I am pretty sure it was fixed by a recent commit. If it remains, @jdivins please reopen it.
