### ISSUE TITLE
Combining audio track with static image

### ISSUE THREAD

**Issue by daentech** [linkedin/LiTr#32]
We're looking at replacing our aging implementation of FFMpeg with this library, but I couldn't work out from the docs whether it was possible yet to combine a static image with an audio track into a video the length of the audio track. Is that possible? 

Thanks

**Comment by izzytwosheds** [comment]
It is not yet supported out-of-the box, but I believe it is possible to implement without any code changes to core library. You should be able to create a new implementation of MediaSource and Decoder interfaces that will produce empty video frames (for the duration of audio track) and apply a "full screen" BitmapOverlayFilter on top.

**Comment by daentech** [comment]
Great, thanks!
