### ISSUE TITLE
[Enhancement/Question] Trim video

### ISSUE THREAD

**Issue by dmesmin** [linkedin/LiTr#4]
Hi @izzytwosheds,
First thanks for this awesome lib!
I'd like to know your opinion on how one could proceed to add a trim video feature in this lib.
To me, it seems to be quite a big refactor, implying to update all the transcoder classes + TransformaitonJob etc..
How would you do it and is it something you plan on adding in the future ?

**Comment by izzytwosheds** [comment]
Hey,

You are absolutely right - implementing trimming would require quite a bit of changes in track transcoders and external APIs. 

Video track transcoder should be able to:
 - seek to I frame (key frame) before the trim
 - decode P/B frames but not render them until trim start  time is reached
 - transcode until trim end time is reached

Video trimming is easy. Audio trimming is not. Audio frames have duration (1024 samples, AFAIR), which will make things very painful. I have a feeling we will have to do some audio frame repackaging. Audio track transcoder should be able to:
 - seek to audio frame that overlaps presentation time of video frame at start of a trim
 - decode audio frame into PCM
 - take N samples from audio frame after the trim position
 - take 1024 - N samples from next audio frame
 - put both samples together, send that to encoder
 - transcode until trim end position is reached
 - encode part of the last frame

API wise I am trying to come up with generic enough API that will allow track wise trimming. That would allow us to do things like replace audio track in a video with trimmed audio track from another video/audio. 

Trimming is something we want to have LiTr do. No idea when that will happen, though. Do you have any urgency? Do you feel comfortable implementing it?

**Comment by dmesmin** [comment]
Hi @izzytwosheds,
Sorry but I don't think I'll have the time to implement it atm, especially given the complexity to trim the audio track. 
Thanks for your insightful answer though! it's helpful to understand how to make the feature

**Comment by izzytwosheds** [comment]
I totally understand. Trimming is a pretty non-trivial task and will probably end up being time consuming. Stay tuned, then. I will get to implementing it at some point. :)

**Comment by izzytwosheds** [comment]
https://github.com/linkedin/LiTr/pull/71
