### ISSUE TITLE
MediaTransformer.transform does not accept null targetVideoFormat

### ISSUE THREAD

**Issue by theseafaringturtle** [linkedin/LiTr#6]
Passing null as targetVideoFormat to MediaTransformer.transform(...) causes a NullPointerException at TranscoderUtils.getEstimatedTargetVideoFileSize, where the parameter is annotated to be @NonNull.

Thanks again for the library, it saves us a lot of time.

**Comment by izzytwosheds** [comment]
Nice catch! Will be fixed in the next update.

**Comment by izzytwosheds** [comment]
Question: what behavior would guys expect when targetVideoFormat is null, but there are filters present? Should filters be applied without changing video resolution/bitrate? 
Current contract is that passing null for a target bypasses any modifications to that type of track, it simply uses a "passthrough" transcoder, which reads frames and writes them "as is"

**Comment by theseafaringturtle** [comment]
Hi, yes, I think it would be reasonable to expect the filters to be applied without changing the encoding parameters.

**Comment by izzytwosheds** [comment]
This should be fixed with the latest patch. It will be in the next release. Let me know how it work out for you guys.
