### ISSUE TITLE
Applying Grayscale GLFilter removes BitmapOverlayFilters

### ISSUE THREAD

**Issue by EllingtonKirby** [linkedin/LiTr#67]
Hi there,

I am using LiTr to transcode videos and apply video overlays, in the 1.4.3 update I have found a bug.

Applying a `GrayscaleFilter` seems to prevent `BitmapOverlayFilter` from being applied. We apply the filters as such
```
                if (targetTrack is MediaTrackSettings.VideoSettings) {
                    val overlayFilters: MutableList<GlFilter> = overlays.map {
                        val bitmap = BitmapFactory.decodeFile(it.filepath)
                        BitmapOverlayFilter(bitmap, Transform(PointF(1f, 1f), PointF(.5f, .5f), 0f))
                    }.toMutableList()
                    overlayFilters.apply {
                        if (applyGrayscaleFilter) {
                            add(GrayscaleFilter())
                        }
                    }
                    setRenderer(GlVideoRenderer(overlayFilters))
                }
```

Previously, on version 1.3.2, adding multiple filters (when `applyGrayscaleFilter` is true) was working as intended for us. 

Is there an issue in how I am applying the filters? Or perhaps a bug here.

**Comment by izzytwosheds** [comment]
Filter ordering matters, since it defines a Z order. So usually, implementations of `GlFrameRenderFilter` (such as `GrayscaleFilter`) should be applied first, so that video is rendered underneath bitmaps. I tried that, it works for me. Discovered an unrelated bug, which I will be fixing, so thank you. :)

**Comment by EllingtonKirby** [comment]
Thank you! Will try that

**Comment by EllingtonKirby** [comment]
Works! Closing
