### ISSUE TITLE
Guidance for improving time taken in video compression

### ISSUE THREAD

**Issue by purnima-tal** [linkedin/LiTr#69]
Sharing some statistics that I observed using this library
2.32 MB -> 1.05 MB in 3 sec
4.5 MB -> 2.359 MB in 10 sec
38.2 MB -> 21 MB in 75 sec

KEY_BIT_RATE - 0.5 times of original bit rate
KEY_I_FRAME_INTERVAL - 5
KEY_FRAME_RATE - 30

I tried with keeping and modifying dimension as well.
Time taken for smaller videos is great but i have concern for larger videos.
Please guide how can I lessen the time required for compressing larger videos.

**Comment by purnima-tal** [comment]
By larger I mean size of the video. I installed 1 application to check codec, it showed codec as Advanced Video Codec for all videos.
The videos which are taking more time (>1 min) are having larger size (>40MB) but its resolution (width and height) is low. May be these videos are already compressed. I checked other larger sized videos ~50MB whose resolution is also high, they took lesser time ~15 SEC. Do we have a way to figure out that the video is already compressed and no more compression is required?

**Comment by izzytwosheds** [comment]
LiTr does not automatically skip transcoding, and that is done on purpose - we believe that this should be done by clients before calling LiTr, as such decisions are usually driven by client's business logic. On some occasions, clients might need to do an opposite and increase resolution/bitrate - for example, to upscale a video after editing it.
Is it possible to share those videos? We could investigate on our end.
