### ISSUE TITLE
Trimmer seems te decode all leading data

### ISSUE THREAD

**Issue by niekdev** [linkedin/LiTr#80]
Whenever I want to trim the last 30 seconds of a 12 minute video, the actual encoding starts after about 6 minutes. It feels like the library is processing all of the (useless) 11 and half minute of footage, that it isn't actually seeking to 11:30 to skip the leading data. 

I'd expect the transcoder to seek to the nearest key frame (just before the provided start time) and starts to decode from there.

**My reproduction steps:**
1) Record a 12 minute video on my device
2) Open the demo app
3) Select "Transcode Video/Audio (GL Renderer)"
4) Pick my 12 minute long video
5) Trim the video so that only the last 30 seconds of the video are selected
6) Click on the "transcode" button

**Current behaviour:**
It takes about 6 minutes before my video starts to encode

**Expected behaviour:**
My video starts to encode (almost, since seeking might take some time depending on the key frame interval) instantaneously

**Environment:** 
Device: Pixel 3
OS: Android 11
LiTr version: 1.4.4

**Comment by izzytwosheds** [comment]
Thank you for reporting this. Current trimming logic is supposed to fast forward to the beginning of trim segment to avoid the behavior described here. We will double check. What device is this happening on?

**Comment by niekdev** [comment]
> Thank you for reporting this. Current trimming logic is supposed to fast forward to the beginning of trim segment to avoid the behavior described here. We will double check. What device is this happening on?

Apologies for not specifying, I updated the issue description with the following:

**Environment:** 
Device: Pixel 3
OS: Android 11
LiTr version: 1.4.4

**Comment by izzytwosheds** [comment]
Looks like `seekTo` was not working that early in transformation process. Fix is in flight. Thank you again for catching this, this is a very nice performance improvement!

**Comment by niekdev** [comment]
Awesome, glad to hear that!

**Comment by niekdev** [comment]
https://github.com/linkedin/LiTr/commit/e79716b84669978511c788c6bafd076789b287b6 fixed this issue, closing this ticket.
