### ISSUE TITLE
Unresolved reference: GlFilter

### ISSUE THREAD

**Issue by Ma7moudHatem** [linkedin/LiTr#99]
I was using the following dependencies in my project:

`def litr_version = '1.4.6'`
 ` implementation "com.linkedin.android.litr:litr:$litr_version"`
  `implementation "com.linkedin.android.litr:litr-filters:$litr_version"`

And I have the following import and usage in one of the project classes:
`import com.linkedin.android.litr.filter.GlFilter`

Everything was working fine and the project compiles and builds correctly with the previous code.
Now after updating the dependencies to version`1.4.8`, I get the following exception
`Unresolved reference: GlFilter` on the import line.

More Info:
`Android Studio 4.1.2`
`Kotlin 1.4.30`
`Compile SDK 29`

**Comment by izzytwosheds** [comment]
Thank you for reporting this! Looking into this right now. We recently moved hosting from Bintray to Sonatype, this might be the reason.

**Comment by izzytwosheds** [comment]
Strange, I cannot reproduce it on my end. GlFilter should live inside `litr`, so if other classes are not breaking, that should not be breaking, either. Did you try a clean build?

**Comment by Ma7moudHatem** [comment]
Sorry, it's my mistake, in my case, I should use `api` instead of `implementation`, because I'm using the `GlFilter` in a module that depends on another module that uses the LiTr dependencies. so I'll close the issue.

@izzytwosheds thanks for your collaboration.
